apiVersion: v1
kind: Service
metadata:
  name: graylog-service
spec:
  selector:
    app: graylog 
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "1514"
      port: 1514
      targetPort: 1514
    - name: 1514-udp
      port: 1514
      protocol: UDP
      targetPort: 1514
    - name: "12201"
      port: 12201
      targetPort: 12201
    - name: 12201-udp
      port: 12201
      protocol: UDP
      targetPort: 12201
    - name: "5044"
      port: 5044
      targetPort: 5044
 

